# Generated by Django 4.2.11 on 2024-05-01 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foodapp', '0002_remove_item_item_desc_remove_item_item_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_desc',
            field=models.CharField(blank=True, max_length=122, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='item_name',
            field=models.CharField(blank=True, max_length=122, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='item_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
